name: CI + Build Workflow

on:
  push:
    branches:
      - main
    paths:
      - "app/**"
      - "tests/**"
      - "Dockerfile"
      - ".github/workflows/ci-build.yml"

  pull_request:
    branches:
      - main
    types: [opened, synchronize, reopened]
    paths:
      - "app/**"
      - "tests/**"
      - "Dockerfile"
      - ".github/workflows/ci-build.yml"

  workflow_dispatch:

env:
  AWS_REGION: us-east-1
  ECR_REPOSITORY: githubactions-demo
  IMAGE_TAG: latest

jobs:
  verify-and-build:
    runs-on: ubuntu-latest

    steps:
      # ================= CI PART =================
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.12"

      - name: Run tests
        run: python -m unittest discover -s tests -v

      - name: Run Trivy security scan
        uses: aquasecurity/trivy-action@0.24.0
        with:
          scan-type: fs
          severity: HIGH,CRITICAL
          exit-code: 1

      # ================= BUILD PART =================
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build Docker image
        run: docker build -t $ECR_REPOSITORY:$IMAGE_TAG .

      - name: Tag image for ECR
        run: |
          ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
          docker tag $ECR_REPOSITORY:$IMAGE_TAG \
          $ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPOSITORY:$IMAGE_TAG

      - name: Push image to ECR
        run: |
          ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
          docker push $ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPOSITORY:$IMAGE_TAG

      # ================= STATUS CHECK =================
      - name: Set status success
        if: success()
        run: echo "CI + Build Succeeded ✅"

      - name: Set status failure
        if: failure()
        run: echo "CI + Build Failed ❌"
