name: 02 CI Workflow

on:
  push:
    paths:
      - "app/**"
      - "tests/**"
      - ".github/workflows/02-ci.yml"

  pull_request:
    branches:
      - main
    types: [opened, synchronize, reopened]
    paths:
      - "app/**"
      - "tests/**"
      - ".github/workflows/02-ci.yml"

  workflow_dispatch:

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v6

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.12"

      - name: Run tests
        run: python -m unittest discover -s tests -v