name: Deploy to EC2

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Setup SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_KEY }}" > ~/.ssh/key.pem
          chmod 400 ~/.ssh/key.pem

      - name: Add EC2 to known hosts
        run: |
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

      - name: AWS ECR Login
        run: |
          ssh -i ~/.ssh/key.pem ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} \
          "aws ecr get-login-password --region us-east-1 | \
          docker login --username AWS --password-stdin 011122071814.dkr.ecr.us-east-1.amazonaws.com"

      - name: Pull Docker Image
        run: |
          ssh -i ~/.ssh/key.pem ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} \
          "docker pull 011122071814.dkr.ecr.us-east-1.amazonaws.com/githubactions-demo:latest"

      - name: Stop Old Container
        run: |
          ssh -i ~/.ssh/key.pem ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} \
          "docker stop tiny-health-container || true"

      - name: Remove Old Container
        run: |
          ssh -i ~/.ssh/key.pem ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} \
          "docker rm tiny-health-container || true"

      - name: Run New Container
        run: |
          ssh -i ~/.ssh/key.pem ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} \
          "docker run -d --name tiny-health-container -p 8000:8000 \
          <ACCOUNT_ID>.dkr.ecr.us-east-1.amazonaws.com/githubactions-demo:latest"

      - name: Cleanup Images
        run: |
          ssh -i ~/.ssh/key.pem ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} \
          "docker image prune -f"
