name: Deploy Workflow

on:
  workflow_run:
    workflows: ["CI + Build + Push to ECR"]
    types: [completed]

env:
  AWS_REGION: us-east-1
  ECR_REPOSITORY: githubactions-demo
  IMAGE_TAG: latest
  CONTAINER_NAME: tiny-health-container
  APP_PORT: "8000"

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      # ================= AWS LOGIN =================
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      # ================= GET ACCOUNT ID =================
      - name: Get AWS Account ID
        id: account
        run: echo "account_id=$(aws sts get-caller-identity --query Account --output text)" >> $GITHUB_OUTPUT

      # ================= PULL IMAGE =================
      - name: Pull Docker image
        run: |
          docker pull ${{ steps.account.outputs.account_id }}.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPOSITORY:$IMAGE_TAG

      # ================= RUN CONTAINER =================
      - name: Run container
        run: |
          docker run -d \
            --name $CONTAINER_NAME \
            -p $APP_PORT:8000 \
            ${{ steps.account.outputs.account_id }}.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPOSITORY:$IMAGE_TAG

      # ================= DEBUG =================
      - name: Show containers
        run: docker ps -a

      - name: Show logs
        run: docker logs $CONTAINER_NAME || true

      # ================= SMOKE TEST =================
      - name: Wait for app
        run: sleep 5

      - name: Health check
        run: curl --fail http://127.0.0.1:$APP_PORT/health

      # ================= CLEANUP =================
      - name: Cleanup
        if: always()
        run: docker rm -f $CONTAINER_NAME || true
